/**
 * 新增知识主题的结构化 spec（候选包生成器的数据真理源）。
 * 每条 source 的 url/编号已在联网深核研究中逐条核对；没把握的标 status='source_pack_review'。
 * 录入新主题 = 往 THREAD_SPECS 追加一条，再跑 build_candidate_packs.ts。
 */

export type SourceRole =
  | 'signal'
  | 'official_definition'
  | 'transcript_context'
  | 'paper_foundation'
  | 'implementation_signal';

export interface SourceSpec {
  id: string;
  role: SourceRole;
  sourceKind: string;
  sourceOwner: string;
  url: string;
  title: string;
  publishedAt?: string | null;
  whyRelevant: string;
  confidence: number;
  evidenceQuote?: string | null;
  reviewNotes?: string;
  /** 默认 verified；没把握的源标 source_pack_review / needs_capture，不冒充。 */
  status?: 'verified' | 'source_pack_review' | 'needs_capture';
}

export interface EdgeSpec {
  fromId: string;
  toId: string;
  relationType: string;
  confidence: number;
  evidenceNote: string;
}

export interface ThreadSpec {
  slug: string;
  title: string;
  updatedAt: string;
  category: string;
  tags: string[];
  aliases: string[];
  definitionDraft: string;
  whyNow: string;
  useBoundary: string;
  sources: SourceSpec[];
  edges: EdgeSpec[];
  reviewNotes: string;
}

const RAG: ThreadSpec = {
  slug: 'rag',
  title: 'Retrieval-Augmented Generation (RAG)',
  updatedAt: '2026-06-21',
  category: 'agentic_infrastructure',
  tags: ['retrieval', 'rag', 'embeddings', 'reranking', 'grounding'],
  aliases: ['Retrieval-Augmented Generation', 'RAG', '检索增强生成', 'retrieval augmented generation'],
  definitionDraft:
    'Retrieval-Augmented Generation connects an LLM to an external non-parametric knowledge store: at generation time a retriever fetches relevant passages and feeds them as context, grounding the answer in citable sources rather than only the model’s parametric memory.',
  whyNow:
    'After the 2024–2025 “long context vs RAG” debate, the consensus is that RAG did not die but evolved—on production retrieval loads it is cheaper and lower-latency than stuffing everything into the window, and remains the main way to ground LLMs in private/real-time data without retraining.',
  useBoundary:
    'Focus on the retrieval engineering chain itself: recall (BM25/dense/hybrid), reranking, chunking, citation grounding and RAG evaluation. Exclude multi-hop autonomous research agents (that is the deep-research thread) and runtime context-window management (context-engineering).',
  sources: [
    // paper_foundation
    {
      id: 'rag_lewis_2020',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Lewis et al., FAIR/UCL)',
      url: 'https://arxiv.org/abs/2005.11401',
      title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
      publishedAt: '2020-05',
      whyRelevant: 'RAG 原论文，提出并命名“检索增强生成”，在开放域 QA 上刷 SOTA。',
      confidence: 1.0,
      evidenceQuote:
        'A general-purpose fine-tuning recipe that combines pre-trained parametric memory with non-parametric memory for language generation.',
    },
    {
      id: 'rag_dpr_2020',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Karpukhin et al., FAIR)',
      url: 'https://arxiv.org/abs/2004.04906',
      title: 'Dense Passage Retrieval for Open-Domain Question Answering',
      publishedAt: '2020-04',
      whyRelevant: 'dense 双编码器召回奠基，比 BM25 top-20 高 9–19%，是 RAG 召回支柱。',
      confidence: 1.0,
    },
    {
      id: 'rag_colbert_2020',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Khattab & Zaharia, Stanford)',
      url: 'https://arxiv.org/abs/2004.12832',
      title: 'ColBERT: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT',
      publishedAt: '2020-04',
      whyRelevant: 'late interaction (MaxSim) 奠基，兼顾 BERT 表达力与可预计算，快两个数量级。',
      confidence: 1.0,
    },
    {
      id: 'rag_ragas_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Es et al.)',
      url: 'https://arxiv.org/abs/2309.15217',
      title: 'RAGAS: Automated Evaluation of Retrieval Augmented Generation',
      publishedAt: '2023-09',
      whyRelevant: 'RAG 评估奠基：无参考的 faithfulness / context relevance 指标套件。',
      confidence: 1.0,
    },
    // official_definition
    {
      id: 'rag_nvidia_def',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'blogs.nvidia.com',
      url: 'https://blogs.nvidia.com/blog/what-is-retrieval-augmented-generation/',
      title: 'What Is Retrieval-Augmented Generation aka RAG',
      publishedAt: '2023',
      whyRelevant: '最广为引用的工业界 RAG 定义页，强调可引用来源 + 降幻觉。',
      confidence: 0.95,
    },
    {
      id: 'rag_survey_2023',
      role: 'official_definition',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Gao et al.)',
      url: 'https://arxiv.org/abs/2312.10997',
      title: 'Retrieval-Augmented Generation for Large Language Models: A Survey',
      publishedAt: '2023-12',
      whyRelevant: '最权威 RAG 综述，提出 Naive / Advanced / Modular RAG 范式划分。',
      confidence: 1.0,
    },
    {
      id: 'rag_llamaindex_concepts',
      role: 'official_definition',
      sourceKind: 'official_docs',
      sourceOwner: 'developers.llamaindex.ai',
      url: 'https://developers.llamaindex.ai/python/framework/getting_started/concepts/',
      title: 'LlamaIndex High-Level Concepts (RAG 定义)',
      publishedAt: '2024',
      whyRelevant: '官方文档定义 RAG 五步（加载→索引→存储→检索→生成），工程视角权威。',
      confidence: 0.9,
    },
    // implementation_signal
    {
      id: 'rag_colbert_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/stanford-futuredata',
      url: 'https://github.com/stanford-futuredata/ColBERT',
      title: 'stanford-futuredata/ColBERT',
      publishedAt: null,
      whyRelevant: 'late interaction 检索器参考实现（含 RAGatouille 入口）。',
      confidence: 0.95,
    },
    {
      id: 'rag_dspy_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/stanfordnlp',
      url: 'https://github.com/stanfordnlp/dspy',
      title: 'stanfordnlp/dspy',
      publishedAt: null,
      whyRelevant: '“programming not prompting”，把检索+生成管线声明式编排并自动优化。',
      confidence: 0.95,
    },
    {
      id: 'rag_langchain_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/langchain-ai',
      url: 'https://github.com/langchain-ai/langchain',
      title: 'langchain-ai/langchain',
      publishedAt: null,
      whyRelevant: '最主流 RAG 编排框架，retrievers / 向量库集成生态。',
      confidence: 0.95,
    },
    {
      id: 'rag_cohere_rerank',
      role: 'implementation_signal',
      sourceKind: 'official_docs',
      sourceOwner: 'docs.cohere.com',
      url: 'https://docs.cohere.com/docs/rerank-overview',
      title: 'Cohere Rerank Overview',
      publishedAt: '2024',
      whyRelevant: '商用 rerank 端点官方文档，召回后重排把 top-N 收敛到 top-K。',
      confidence: 0.9,
    },
    {
      id: 'rag_dspy_paper',
      role: 'implementation_signal',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Khattab et al.)',
      url: 'https://arxiv.org/abs/2310.03714',
      title: 'DSPy: Compiling Declarative Language Model Calls into Self-Improving Pipelines',
      publishedAt: '2023-10',
      whyRelevant: 'DSPy 方法论论文，把 RAG 管线作为可优化的文本变换图。',
      confidence: 1.0,
    },
    // signal
    {
      id: 'rag_anthropic_contextual',
      role: 'signal',
      sourceKind: 'official_blog',
      sourceOwner: 'anthropic.com',
      url: 'https://www.anthropic.com/news/contextual-retrieval',
      title: 'Introducing Contextual Retrieval',
      publishedAt: '2024-09',
      whyRelevant: 'chunking 关键信号：上下文化 chunk + BM25 + rerank 叠加，top-20 失败率降 67%。',
      confidence: 1.0,
    },
    {
      id: 'rag_longctx_vs_rag_2025',
      role: 'signal',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org',
      url: 'https://arxiv.org/abs/2501.01880',
      title: 'Long Context vs. RAG for LLMs: An Evaluation and Revisits',
      publishedAt: '2025-01',
      whyRelevant: '“长上下文 vs RAG”争论的实证再评估，标志 RAG 边界讨论。',
      confidence: 0.85,
      status: 'source_pack_review',
      reviewNotes: '编号已核；作为边界讨论信号保留，结论性表述发布前再核。',
    },
    {
      id: 'rag_lighton_not_dead_2025',
      role: 'signal',
      sourceKind: 'blog',
      sourceOwner: 'lighton.ai',
      url: 'https://lighton.ai/lighton-blogs/rag-is-dead-long-live-rag-retrieval-in-the-age-of-agents',
      title: 'RAG is Dead, Long Live RAG: Retrieval in the Age of Agents',
      publishedAt: '2025',
      whyRelevant: '行业反驳“RAG 已死”的代表性讨论，agent 时代检索仍是核心。',
      confidence: 0.8,
      status: 'source_pack_review',
    },
    // transcript_context
    {
      id: 'rag_lewis_mlst_2024',
      role: 'transcript_context',
      sourceKind: 'podcast',
      sourceOwner: 'Machine Learning Street Talk',
      url: 'https://podcasts.apple.com/mm/podcast/patrick-lewis-cohere-retrieval-augmented-generation/id1510472996?i=1000669735527',
      title: 'Patrick Lewis (Cohere) — Retrieval Augmented Generation (MLST)',
      publishedAt: '2024-06',
      whyRelevant: 'RAG 命名者本人讲 RAG 起源 / 命名 / 评估挑战。',
      confidence: 0.9,
    },
    {
      id: 'rag_jerryliu_latentspace_2023',
      role: 'transcript_context',
      sourceKind: 'podcast',
      sourceOwner: 'Latent Space (swyx)',
      url: 'https://www.latent.space/p/llamaindex',
      title: 'RAG Is A Hack — with Jerry Liu from LlamaIndex',
      publishedAt: '2023-10',
      whyRelevant: 'LlamaIndex CEO 讲为何 RAG 是生产 AI 核心、“text 是通用接口”。',
      confidence: 0.9,
    },
  ],
  edges: [
    {
      fromId: 'rag_dpr_2020',
      toId: 'rag_lewis_2020',
      relationType: 'foundation_dependency',
      confidence: 0.9,
      evidenceNote: 'DPR 的 dense 双编码器正是 RAG 原论文采用的神经检索器，召回支撑生成。',
    },
    {
      fromId: 'rag_colbert_2020',
      toId: 'rag_cohere_rerank',
      relationType: 'technique_lineage',
      confidence: 0.75,
      evidenceNote: 'ColBERT 的 late interaction 细粒度打分是商用 rerank 重排环节的学术先驱。',
    },
    {
      fromId: 'rag_anthropic_contextual',
      toId: 'rag_cohere_rerank',
      relationType: 'implements',
      confidence: 0.8,
      evidenceNote: 'Anthropic Contextual Retrieval 实测里 rerank 环节直接用 Cohere reranker。',
    },
    {
      fromId: 'rag_survey_2023',
      toId: 'rag_lewis_2020',
      relationType: 'surveys_extends',
      confidence: 0.85,
      evidenceNote: '综述把原论文的 Naive RAG 作为起点，归纳到 Advanced / Modular RAG 演进谱系。',
    },
    {
      fromId: 'rag_lewis_mlst_2024',
      toId: 'rag_lewis_2020',
      relationType: 'author_explains',
      confidence: 0.85,
      evidenceNote: '原论文一作本人在访谈里讲 RAG 命名由来与评估挑战。',
    },
    {
      fromId: 'rag_ragas_2023',
      toId: 'rag_anthropic_contextual',
      relationType: 'evaluates',
      confidence: 0.75,
      evidenceNote: 'RAGAS 的 context relevance / faithfulness 指标正是 Anthropic 那类 chunking / 检索改进所需的量化评估。',
    },
    {
      fromId: 'rag_longctx_vs_rag_2025',
      toId: 'rag_lighton_not_dead_2025',
      relationType: 'debates',
      confidence: 0.7,
      evidenceNote: '学术实证与行业博客就“长上下文能否取代 RAG”形成对话，结论都是 RAG 进化非消亡。',
    },
    {
      fromId: 'rag_dspy_paper',
      toId: 'rag_dspy_repo',
      relationType: 'implements',
      confidence: 0.85,
      evidenceNote: 'DSPy 论文方法论由同名开源仓库落地。',
    },
  ],
  reviewNotes:
    'Deep-core 2026-06-21: 17 sources / 8 edges, all arXiv ids verified online (2005.11401=Lewis RAG, 2004.04906=DPR, 2004.12832=ColBERT, 2309.15217=RAGAS, 2312.10997=survey, 2310.03714=DSPy). 2 signal sources (long-ctx-vs-rag 2501.01880, LightOn) kept at source_pack_review pending exact-claim recheck. Roles all >=2.',
};

const DEEP_RESEARCH: ThreadSpec = {
  slug: 'deep-research',
  title: 'Deep Research (调研型 agent)',
  updatedAt: '2026-06-21',
  category: 'agentic_infrastructure',
  tags: ['deep-research', 'research-agent', 'agentic-search', 'browsing-agent', 'report-generation'],
  aliases: ['Deep Research', '深度研究', 'research agent', 'DeepSearch', 'DeepResearch'],
  definitionDraft:
    'Deep Research is a class of research agent: given a complex question, the agent autonomously runs a multi-hop loop of plan → iterative web search → read → cross-verify → synthesize a long, cited report, compressing hours of desk research into minutes.',
  whyNow:
    'After Google first shipped it (2024-12) and OpenAI followed (2025-02), Deep Research evolved within a year from a report-writing assistant into an autonomous agent that reasons while it searches and decides how deep to go — the first killer product form that fuses reasoning models with agentic search, and a yardstick (BrowseComp) for long-horizon agent autonomy.',
  useBoundary:
    'Focus on the autonomous multi-hop research loop of a single research task (plan/search/read/verify/synthesize). Exclude general multi-agent collaboration (multi-agent-orchestration) and code-writing agents (agentic-coding).',
  sources: [
    // signal
    {
      id: 'dr_google_deepest_2025',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'techcrunch.com',
      url: 'https://techcrunch.com/2025/12/11/google-launched-its-deepest-ai-research-agent-yet-on-the-same-day-openai-dropped-gpt-5-2/',
      title: 'Google launched its deepest AI research agent yet — same day OpenAI dropped GPT-5.2',
      publishedAt: '2025-12-11',
      whyRelevant: 'Google 把 Deep Research 从写报告助手升级为自治研究 agent，巨头同日对垒的竞速信号。',
      confidence: 0.85,
    },
    {
      id: 'dr_google_max_vb_2026',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'venturebeat.com',
      url: 'https://venturebeat.com/technology/googles-new-deep-research-and-deep-research-max-agents-can-search-the-web-and-your-private-data',
      title: 'Google’s new Deep Research and Deep Research Max agents can search the web and your private data',
      publishedAt: '2026-04',
      whyRelevant: 'Deep Research Max 可接 MCP、查私域数据、单任务 100+ 来源，"整夜跑尽调"形态成型。',
      confidence: 0.85,
    },
    {
      id: 'dr_gemini_first_2024',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'techcrunch.com',
      url: 'https://techcrunch.com/2024/12/11/gemini-can-now-research-deeper/',
      title: 'Gemini can now research deeper',
      publishedAt: '2024-12-11',
      whyRelevant: 'Google 首推 Deep Research 品类的起点报道，确立"agentic 规划 + 浏览"范式。',
      confidence: 0.85,
    },
    // official_definition
    {
      id: 'dr_openai_intro',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'openai.com',
      url: 'https://openai.com/index/introducing-deep-research/',
      title: 'Introducing deep research',
      publishedAt: '2025-02-02',
      whyRelevant: 'OpenAI 官方发布页，给出权威定义：用 reasoning 综合在线信息完成多步研究。',
      confidence: 0.95,
      evidenceQuote:
        'An agent that uses reasoning to synthesize large amounts of online information and complete multi-step research tasks for you.',
    },
    {
      id: 'dr_openai_systemcard',
      role: 'official_definition',
      sourceKind: 'official_docs',
      sourceOwner: 'openai.com',
      url: 'https://cdn.openai.com/deep-research-system-card.pdf',
      title: 'Deep Research System Card',
      publishedAt: '2025-02-25',
      whyRelevant: '官方系统卡，载明模型基于 o3 早期版优化网页浏览、红队与风险缓解。',
      confidence: 0.9,
    },
    {
      id: 'dr_google_blog_2024',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'blog.google',
      url: 'https://blog.google/products/gemini/google-gemini-deep-research/',
      title: 'Try Deep Research and our new experimental model in Gemini',
      publishedAt: '2024-12-11',
      whyRelevant: 'Google 官方博客，阐述 agentic 规划系统把复杂查询拆成研究计划供用户改。',
      confidence: 0.9,
    },
    {
      id: 'dr_anthropic_multiagent',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'anthropic.com',
      url: 'https://www.anthropic.com/engineering/multi-agent-research-system',
      title: 'How we built our multi-agent research system',
      publishedAt: '2025-06-13',
      whyRelevant: 'Claude Research 调研产品的官方实现，orchestrator-worker 并行调研架构（比单 agent +90.2%）。',
      confidence: 0.9,
    },
    // transcript_context
    {
      id: 'dr_srinivas_lex_2024',
      role: 'transcript_context',
      sourceKind: 'podcast',
      sourceOwner: 'Lex Fridman Podcast',
      url: 'https://lexfridman.com/aravind-srinivas-transcript/',
      title: 'Aravind Srinivas: Perplexity CEO on Future of AI, Search & the Internet (Lex Fridman #434)',
      publishedAt: '2024-06',
      whyRelevant: 'Perplexity CEO 阐述"answer engine 而非 search engine"愿景——Deep Research 的产品哲学源头。',
      confidence: 0.9,
    },
    {
      id: 'dr_perplexity_computer_2026',
      role: 'transcript_context',
      sourceKind: 'blog',
      sourceOwner: 'perplexity.ai',
      url: 'https://www.perplexity.ai/hub/blog/the-ai-is-the-computer',
      title: 'The AI is the Computer (Aravind Srinivas)',
      publishedAt: '2026-03',
      whyRelevant: 'Srinivas 阐述把 Deep Research 作为 Perplexity Computer 内的原生 skill。',
      confidence: 0.7,
      status: 'source_pack_review',
      reviewNotes: '搜索见，未单独抓取确认正文与日期，发布前补抓。',
    },
    // paper_foundation
    {
      id: 'dr_react_2022',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Yao et al., ICLR 2023)',
      url: 'https://arxiv.org/abs/2210.03629',
      title: 'ReAct: Synergizing Reasoning and Acting in Language Models',
      publishedAt: '2022-10',
      whyRelevant: '推理-行动交错范式奠基，Deep Research"边想边搜边读"循环的方法学源头。',
      confidence: 1.0,
    },
    {
      id: 'dr_selfask_2022',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Press et al., EMNLP 2023 Findings)',
      url: 'https://arxiv.org/abs/2210.03350',
      title: 'Measuring and Narrowing the Compositionality Gap in Language Models (Self-Ask)',
      publishedAt: '2022-10',
      whyRelevant: 'self-ask：把复杂问题自拆成子问题再答——多跳调研"规划→子查询"的直接前身。',
      confidence: 1.0,
    },
    {
      id: 'dr_searcho1_2025',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (RUC-NLPIR, EMNLP 2025)',
      url: 'https://arxiv.org/abs/2501.05366',
      title: 'Search-o1: Agentic Search-Enhanced Large Reasoning Models',
      publishedAt: '2025-01',
      whyRelevant: '把 agentic RAG + Reason-in-Documents 嵌入推理链——Deep Research 的学术化骨架。',
      confidence: 0.95,
    },
    {
      id: 'dr_browsecomp_2025',
      role: 'paper_foundation',
      sourceKind: 'official_blog',
      sourceOwner: 'openai.com (Wei et al.)',
      url: 'https://openai.com/index/browsecomp/',
      title: 'BrowseComp: A Simple Yet Challenging Benchmark for Browsing Agents',
      publishedAt: '2025-04',
      whyRelevant: '1266 题评测浏览 agent，Deep Research 达 51.5%——衡量"查多深/多自主"的标尺。',
      confidence: 0.9,
    },
    // implementation_signal
    {
      id: 'dr_gptresearcher_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/assafelovic',
      url: 'https://github.com/assafelovic/gpt-researcher',
      title: 'assafelovic/gpt-researcher',
      publishedAt: null,
      whyRelevant: '最流行的开源调研 agent，planner→executors→publisher 流水线，多源带引用长报告。',
      confidence: 0.95,
    },
    {
      id: 'dr_langchain_odr_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/langchain-ai',
      url: 'https://github.com/langchain-ai/open_deep_research',
      title: 'langchain-ai/open_deep_research',
      publishedAt: null,
      whyRelevant: 'LangChain 官方开源 Deep Research agent，跨 LLM/搜索/MCP，登 Deep Research Bench。',
      confidence: 0.9,
    },
    {
      id: 'dr_firecrawl_odr_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/nickscamara',
      url: 'https://github.com/nickscamara/open-deep-research',
      title: 'nickscamara/open-deep-research (Firecrawl 驱动)',
      publishedAt: null,
      whyRelevant: '用 Firecrawl 搜索+抽取喂推理模型的开源 Deep Research clone。',
      confidence: 0.85,
    },
    {
      id: 'dr_jina_deepresearch_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/jina-ai',
      url: 'https://github.com/jina-ai/node-DeepResearch',
      title: 'jina-ai/node-DeepResearch',
      publishedAt: null,
      whyRelevant: 'Jina DeepSearch：search-read-reason 循环跑到找到答案或耗尽 token 预算。',
      confidence: 0.9,
    },
  ],
  edges: [
    {
      fromId: 'dr_react_2022',
      toId: 'dr_searcho1_2025',
      relationType: 'foundation_extends',
      confidence: 0.85,
      evidenceNote: 'Search-o1 把 ReAct 的"推理-行动交错"专门用到大推理模型的自主补知识上。',
    },
    {
      fromId: 'dr_selfask_2022',
      toId: 'dr_openai_intro',
      relationType: 'method_realized_in',
      confidence: 0.75,
      evidenceNote: 'OpenAI Deep Research 的"把问题拆成子任务再逐步研究"正是 self-ask 思想的产品化。',
    },
    {
      fromId: 'dr_browsecomp_2025',
      toId: 'dr_openai_intro',
      relationType: 'benchmark_evaluates',
      confidence: 0.9,
      evidenceNote: 'BrowseComp 是 OpenAI 官方用来量化 Deep Research 浏览-检索能力的基准。',
    },
    {
      fromId: 'dr_openai_intro',
      toId: 'dr_google_blog_2024',
      relationType: 'competitive_followup',
      confidence: 0.85,
      evidenceNote: 'OpenAI 2025.02 发布是对 Google 2024.12 首推 Deep Research 品类的同台跟进。',
    },
    {
      fromId: 'dr_anthropic_multiagent',
      toId: 'dr_langchain_odr_repo',
      relationType: 'architecture_mirrors',
      confidence: 0.75,
      evidenceNote: 'Anthropic orchestrator-worker 并行 subagent 架构与 LangChain 开源实现的多 agent 设计互证。',
    },
    {
      fromId: 'dr_searcho1_2025',
      toId: 'dr_gptresearcher_repo',
      relationType: 'concept_to_implementation',
      confidence: 0.75,
      evidenceNote: 'Search-o1 的 agentic search 循环在 gpt-researcher 的 planner→executors→publisher 工程中落地。',
    },
    {
      fromId: 'dr_gemini_first_2024',
      toId: 'dr_google_max_vb_2026',
      relationType: 'product_evolution',
      confidence: 0.85,
      evidenceNote: '同一产品线从 2024.12 写报告助手演进到 2026.04 整夜自治尽调，体现"自治深度"递进。',
    },
  ],
  reviewNotes:
    'Deep-core 2026-06-21: 17 sources / 7 edges, arXiv ids verified (2210.03629=ReAct, 2210.03350=Self-Ask, 2501.05366=Search-o1). 1 transcript (perplexity computer blog) at source_pack_review pending fulltext capture. OpenAI urls fetched via firecrawl (corp policy blocked direct WebFetch). Roles all >=2.',
};

const MODEL_TRAINING: ThreadSpec = {
  slug: 'model-training',
  title: 'Model Training (全链路)',
  updatedAt: '2026-06-21',
  category: 'foundation_models',
  tags: ['pretraining', 'post-training', 'rlhf', 'scaling-laws', 'alignment'],
  aliases: ['Model Training', '模型训练', 'pretraining', 'post-training', 'RLHF', 'scaling laws'],
  definitionDraft:
    'Full-stack model training is the complete pipeline that turns a large model from zero parameters into a usable assistant: pre-training (self-supervised next-token prediction governed by scaling laws) followed by post-training / alignment (SFT → RLHF → DPO → RLVR/GRPO).',
  whyNow:
    'After Ilya Sutskever declared at NeurIPS 2024 that "pre-training as we know it will end" (data is AI’s fossil fuel and has peaked), the industry’s center of gravity shifted from stacking pre-training data toward post-training / RL / test-time compute — making "how you train" the main battleground for capability differences.',
  useBoundary:
    'Focus on the training-side causes: how scaling laws set pre-training scale, how SFT/RLHF/RLVR/GRPO shape a base model into an assistant. Exclude test-time/inference-time methods themselves (reasoning-models thread).',
  sources: [
    // paper_foundation
    {
      id: 'mt_kaplan_scaling_2020',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Kaplan et al., OpenAI)',
      url: 'https://arxiv.org/abs/2001.08361',
      title: 'Scaling Laws for Neural Language Models',
      publishedAt: '2020-01',
      whyRelevant: '预训练 scaling laws 奠基：损失随规模/数据/算力呈幂律。',
      confidence: 1.0,
    },
    {
      id: 'mt_chinchilla_2022',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Hoffmann et al., DeepMind)',
      url: 'https://arxiv.org/abs/2203.15556',
      title: 'Training Compute-Optimal Large Language Models (Chinchilla)',
      publishedAt: '2022-03',
      whyRelevant: '修正 Kaplan：模型与 token 数应等比放大，多数模型欠训。',
      confidence: 1.0,
    },
    {
      id: 'mt_instructgpt_2022',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Ouyang et al., OpenAI)',
      url: 'https://arxiv.org/abs/2203.02155',
      title: 'Training language models to follow instructions with human feedback (InstructGPT)',
      publishedAt: '2022-03',
      whyRelevant: 'RLHF 三步法（SFT + 奖励模型 + PPO）奠基，ChatGPT 前身。',
      confidence: 1.0,
    },
    {
      id: 'mt_dpo_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Rafailov et al., Stanford)',
      url: 'https://arxiv.org/abs/2305.18290',
      title: 'Direct Preference Optimization (DPO)',
      publishedAt: '2023-05',
      whyRelevant: '免奖励模型直接优化偏好，把 RLHF 化简为分类损失。',
      confidence: 1.0,
    },
    {
      id: 'mt_grpo_deepseekmath_2024',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Shao et al., DeepSeek)',
      url: 'https://arxiv.org/abs/2402.03300',
      title: 'DeepSeekMath (GRPO 出处)',
      publishedAt: '2024-02',
      whyRelevant: 'GRPO 算法首次提出，比 PPO 更省显存的组相对优化。',
      confidence: 1.0,
    },
    {
      id: 'mt_ppo_2017',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Schulman et al., OpenAI)',
      url: 'https://arxiv.org/abs/1707.06347',
      title: 'Proximal Policy Optimization Algorithms (PPO)',
      publishedAt: '2017-07',
      whyRelevant: 'RLHF 默认 RL 算法的源头，后训练 RL 的底层引擎。',
      confidence: 1.0,
    },
    // official_definition
    {
      id: 'mt_deepseek_v3_2024',
      role: 'official_definition',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (DeepSeek-AI)',
      url: 'https://arxiv.org/abs/2412.19437',
      title: 'DeepSeek-V3 Technical Report',
      publishedAt: '2024-12',
      whyRelevant: '671B MoE，14.8T token 预训练 + SFT + RL，全链路成本工程范本。',
      confidence: 1.0,
    },
    {
      id: 'mt_deepseek_r1_2025',
      role: 'official_definition',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (DeepSeek-AI)',
      url: 'https://arxiv.org/abs/2501.12948',
      title: 'DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via RL',
      publishedAt: '2025-01',
      whyRelevant: '纯 RL(GRPO) 即可涌现 CoT，训练侧造就推理能力。',
      confidence: 1.0,
    },
    {
      id: 'mt_instructgpt_blog_2022',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'openai.com',
      url: 'https://openai.com/index/instruction-following/',
      title: 'Aligning language models to follow instructions (InstructGPT 官方博客)',
      publishedAt: '2022-01',
      whyRelevant: 'RLHF 落地为 API 默认模型的官方说明。',
      confidence: 0.9,
    },
    {
      id: 'mt_llama3_2024',
      role: 'official_definition',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Meta AI)',
      url: 'https://arxiv.org/abs/2407.21783',
      title: 'The Llama 3 Herd of Models',
      publishedAt: '2024-07',
      whyRelevant: '开放权重旗舰的预训练数据 + 后训练流程完整披露。',
      confidence: 1.0,
    },
    // signal
    {
      id: 'mt_ilya_neurips_2024',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'techmeme.com (Ilya Sutskever @ NeurIPS 2024)',
      url: 'https://www.techmeme.com/241213/p33',
      title: 'Ilya Sutskever NeurIPS 2024: "Pre-training as we know it will end" (peak data)',
      publishedAt: '2024-12-13',
      whyRelevant: '预训练范式见顶信号，重心转向后训练/RL/推理时算力。',
      confidence: 0.85,
    },
    {
      id: 'mt_tulu3_2024',
      role: 'signal',
      sourceKind: 'official_blog',
      sourceOwner: 'allenai.org',
      url: 'https://allenai.org/blog/tulu-3-technical',
      title: 'Tülu 3: The next era in open post-training',
      publishedAt: '2024-11-21',
      whyRelevant: '全开源后训练四阶段配方 SFT→DPO→RLVR，开源后训练崛起的信号。',
      confidence: 0.9,
    },
    // transcript_context
    {
      id: 'mt_schulman_dwarkesh_2024',
      role: 'transcript_context',
      sourceKind: 'podcast',
      sourceOwner: 'Dwarkesh Podcast',
      url: 'https://www.dwarkesh.com/p/john-schulman',
      title: 'John Schulman — Reasoning, RLHF & plan for 2027 AGI',
      publishedAt: '2024-05-15',
      whyRelevant: 'PPO/RLHF 创造者亲述后训练如何"驯服 shoggoth"。',
      confidence: 0.8,
      status: 'source_pack_review',
      reviewNotes: '永久链高置信，落盘前再 fetch 确认 200。',
    },
    {
      id: 'mt_karpathy_deepdive_2025',
      role: 'transcript_context',
      sourceKind: 'video',
      sourceOwner: 'YouTube (Andrej Karpathy)',
      url: 'https://www.youtube.com/watch?v=7xTGNNLPyMI',
      title: 'Deep Dive into LLMs like ChatGPT',
      publishedAt: '2025-02-05',
      whyRelevant: 'Base→SFT→RLHF 三阶段最权威科普，附 "RLHF is just barely RL" 论点。',
      confidence: 0.8,
      status: 'source_pack_review',
      reviewNotes: '视频 ID 高置信，落盘前再确认在线。',
    },
    // implementation_signal
    {
      id: 'mt_nanogpt_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/karpathy',
      url: 'https://github.com/karpathy/nanoGPT',
      title: 'karpathy/nanoGPT',
      publishedAt: null,
      whyRelevant: '~300 行复现 GPT-2 预训练，理解预训练循环的最小范本。',
      confidence: 0.95,
    },
    {
      id: 'mt_trl_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/huggingface',
      url: 'https://github.com/huggingface/trl',
      title: 'huggingface/trl — Transformer Reinforcement Learning',
      publishedAt: null,
      whyRelevant: 'SFTTrainer/DPOTrainer/GRPOTrainer 一站式后训练栈。',
      confidence: 0.95,
    },
    {
      id: 'mt_open_instruct_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/allenai',
      url: 'https://github.com/allenai/open-instruct',
      title: 'allenai/open-instruct (Tülu 3 训练代码库)',
      publishedAt: null,
      whyRelevant: 'RLVR/DPO/SFT 全开源后训练实现，配 Tülu 3 论文。',
      confidence: 0.9,
    },
  ],
  edges: [
    {
      fromId: 'mt_chinchilla_2022',
      toId: 'mt_kaplan_scaling_2020',
      relationType: 'corrects_refines',
      confidence: 0.9,
      evidenceNote: 'Chinchilla 修正 Kaplan 的算力分配结论，指出模型与数据应等比放大。',
    },
    {
      fromId: 'mt_instructgpt_2022',
      toId: 'mt_ppo_2017',
      relationType: 'builds_on',
      confidence: 0.9,
      evidenceNote: 'InstructGPT 的 RLHF 第三步直接用 Schulman 的 PPO 做策略优化。',
    },
    {
      fromId: 'mt_dpo_2023',
      toId: 'mt_instructgpt_2022',
      relationType: 'simplifies_alternative',
      confidence: 0.85,
      evidenceNote: 'DPO 把 InstructGPT 的"奖励模型+PPO"两步化简为单一分类损失。',
    },
    {
      fromId: 'mt_deepseek_r1_2025',
      toId: 'mt_grpo_deepseekmath_2024',
      relationType: 'builds_on',
      confidence: 0.9,
      evidenceNote: 'R1 直接采用 DeepSeekMath 提出的 GRPO 作为 RL 框架。',
    },
    {
      fromId: 'mt_deepseek_r1_2025',
      toId: 'mt_deepseek_v3_2024',
      relationType: 'builds_on',
      confidence: 0.9,
      evidenceNote: 'R1 以 V3-Base 为底座做纯 RL 后训练。',
    },
    {
      fromId: 'mt_trl_repo',
      toId: 'mt_grpo_deepseekmath_2024',
      relationType: 'implements',
      confidence: 0.85,
      evidenceNote: 'TRL 的 GRPOTrainer 实现了 DeepSeek 提出、用于训 R1 的 GRPO。',
    },
    {
      fromId: 'mt_tulu3_2024',
      toId: 'mt_dpo_2023',
      relationType: 'implements_extends',
      confidence: 0.8,
      evidenceNote: 'Tülu 3 四阶段配方把 DPO 串进 SFT→DPO→RLVR 流水线。',
    },
    {
      fromId: 'mt_ilya_neurips_2024',
      toId: 'mt_chinchilla_2022',
      relationType: 'challenges_context',
      confidence: 0.7,
      evidenceNote: '"peak data" 宣告 Chinchilla 式"加数据加规模"范式逼近天花板。',
    },
  ],
  reviewNotes:
    'Deep-core 2026-06-21: 18 sources / 8 edges, all arXiv ids verified (2001.08361 Kaplan, 2203.15556 Chinchilla, 2203.02155 InstructGPT, 2305.18290 DPO, 2402.03300 GRPO, 1707.06347 PPO, 2412.19437 V3, 2501.12948 R1, 2407.21783 Llama3). 2 transcripts (Schulman/Karpathy) at source_pack_review pending re-fetch. Roles all >=2.',
};

const SELF_EVOLVING: ThreadSpec = {
  slug: 'self-evolving-agents',
  title: 'Self-Evolving Agents (自进化 agent 系统)',
  updatedAt: '2026-06-21',
  category: 'agentic_infrastructure',
  tags: ['self-improvement', 'self-evolving', 'reflexion', 'self-refine', 'open-ended'],
  aliases: ['Self-Evolving Agents', '自进化智能体', 'self-improving agents', 'recursive self-improvement'],
  definitionDraft:
    'Self-evolving agents improve themselves after deployment based on interaction data and environment feedback, rather than staying static with pre-deployment human configuration — improving above the weights via verbal reflection, accumulated skills/memory, or rewriting their own prompts, tools and code.',
  whyNow:
    'In 2025 the Darwin Gödel Machine let an agent rewrite its own code and lifted SWE-bench from 20% to 50%, the first engineering proof that open-ended recursive self-improvement is achievable for coding agents; MIT Technology Review listed "AI learning to improve itself" as a defining 2025 direction.',
  useBoundary:
    'Focus on agents that improve themselves at runtime (self-reflection, skill/memory accumulation, self-modifying code). Exclude training-side self-reward/self-distillation (model-training) and human-designed automation loops (loop-engineering).',
  sources: [
    // paper_foundation
    {
      id: 'se_reflexion_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Shinn et al., NeurIPS 2023)',
      url: 'https://arxiv.org/abs/2303.11366',
      title: 'Reflexion: Language Agents with Verbal Reinforcement Learning',
      publishedAt: '2023-03',
      whyRelevant: '自我反思修正奠基：用语言反馈写进 episodic memory，不更新权重就提升下一轮决策。',
      confidence: 1.0,
    },
    {
      id: 'se_voyager_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Wang et al., NVIDIA/Caltech)',
      url: 'https://arxiv.org/abs/2305.16291',
      title: 'Voyager: An Open-Ended Embodied Agent with Large Language Models',
      publishedAt: '2023-05',
      whyRelevant: '技能/记忆积累标杆：自动课程 + 不断增长的可执行代码 skill library + 迭代自我验证。',
      confidence: 1.0,
    },
    {
      id: 'se_star_2022',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Zelikman et al.)',
      url: 'https://arxiv.org/abs/2203.14465',
      title: 'STaR: Bootstrapping Reasoning With Reasoning',
      publishedAt: '2022-03',
      whyRelevant: '自举推理早期范式：用自己生成的正确 rationale 反哺自身，奠定"自我提升"循环。',
      confidence: 1.0,
    },
    {
      id: 'se_self_refine_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Madaan et al.)',
      url: 'https://arxiv.org/abs/2303.17651',
      title: 'Self-Refine: Iterative Refinement with Self-Feedback',
      publishedAt: '2023-03',
      whyRelevant: '同一 LLM 充当生成者/反馈者/精炼者，无需训练即迭代自我修正。',
      confidence: 1.0,
    },
    {
      id: 'se_godel_machine_2003',
      role: 'paper_foundation',
      sourceKind: 'academic_page',
      sourceOwner: 'people.idsia.ch (Jürgen Schmidhuber)',
      url: 'https://people.idsia.ch/~juergen/gmweb2/gmweb2.html',
      title: 'Gödel Machines: Self-Referential Universal Problem Solvers',
      publishedAt: '2003',
      whyRelevant: '自我改写代码做"可证明有益"改进的理论谱系起点，DGM 谱系命名来源。',
      confidence: 0.9,
    },
    // official_definition
    {
      id: 'se_dgm_2025',
      role: 'official_definition',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Zhang, Hu, Lu, Lange, Clune — Sakana/UBC)',
      url: 'https://arxiv.org/abs/2505.22954',
      title: 'Darwin Gödel Machine: Open-Ended Evolution of Self-Improving Agents',
      publishedAt: '2025-05',
      whyRelevant: '自改代码 agent 代表定义：维护变体谱系、经验证改进，SWE-bench 20%→50%。',
      confidence: 1.0,
    },
    {
      id: 'se_adas_2024',
      role: 'official_definition',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Hu, Lu, Clune)',
      url: 'https://arxiv.org/abs/2408.08435',
      title: 'Automated Design of Agentic Systems (ADAS / Meta Agent Search)',
      publishedAt: '2024-08',
      whyRelevant: '自动 agent 设计：meta agent 在不断扩张的归档上编程出更强 agent。',
      confidence: 1.0,
    },
    {
      id: 'se_survey_comprehensive_2025',
      role: 'official_definition',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Fang et al., EvoAgentX)',
      url: 'https://arxiv.org/abs/2508.07407',
      title: 'A Comprehensive Survey of Self-Evolving AI Agents',
      publishedAt: '2025-08',
      whyRelevant: '统一概念框架，把自进化 agent 抽象成一个反馈闭环，本主题的定义性综述。',
      confidence: 1.0,
    },
    {
      id: 'se_survey_selfevolving_2025',
      role: 'official_definition',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org',
      url: 'https://arxiv.org/abs/2507.21046',
      title: 'A Survey of Self-Evolving Agents: What/When/How/Where to Evolve',
      publishedAt: '2025-07',
      whyRelevant: '系统梳理"何处可进化"分类法，给出 2022–2025 演化版图。',
      confidence: 1.0,
    },
    // transcript_context
    {
      id: 'se_clune_talk',
      role: 'transcript_context',
      sourceKind: 'video',
      sourceOwner: 'YouTube (Jeff Clune)',
      url: 'https://www.youtube.com/watch?v=tP5AB5GgZAE',
      title: 'Jeff Clune — Open-Ended and AI-Generating Algorithms in the Era of Foundation Models',
      publishedAt: '2025-05',
      whyRelevant: 'DGM/ADAS/AI Scientist 第一人称讲解自我改进 agent 与开放式算法三支柱。',
      confidence: 0.85,
    },
    {
      id: 'se_jimfan_grasp_2023',
      role: 'transcript_context',
      sourceKind: 'talk',
      sourceOwner: 'UPenn GRASP (Jim Fan)',
      url: 'https://www.grasp.upenn.edu/events/fall-2023-grasp-sfi-jim-fan/',
      title: 'Jim Fan — Generalist Agents in Open-Ended Worlds',
      publishedAt: '2023',
      whyRelevant: 'Voyager 团队负责人讲终身学习 agent 如何在情境中自我改进。',
      confidence: 0.85,
    },
    // signal
    {
      id: 'se_mit_techreview_2025',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'technologyreview.com (Grace Huckins)',
      url: 'https://www.technologyreview.com/2025/08/06/1121193/five-ways-that-ai-is-learning-to-improve-itself/',
      title: 'Five ways that AI is learning to improve itself',
      publishedAt: '2025-08-06',
      whyRelevant: '权威媒体把"AI 自我改进"作为趋势，点名 DGM/AI Scientist/AlphaEvolve。',
      confidence: 0.9,
    },
    {
      id: 'se_sakana_dgm_blog_2025',
      role: 'signal',
      sourceKind: 'official_blog',
      sourceOwner: 'sakana.ai',
      url: 'https://sakana.ai/dgm/',
      title: 'The Darwin Gödel Machine: AI that improves itself by rewriting its own code',
      publishedAt: '2025-05',
      whyRelevant: '第一手发布稿，给出 SWE-bench 20%→50%、Polyglot 14.2%→30.7% 的自我改进证据。',
      confidence: 0.95,
    },
    {
      id: 'se_decoder_dgm_2025',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'the-decoder.com',
      url: 'https://the-decoder.com/sakana-ais-darwin-godel-machine-evolves-by-rewriting-its-own-code-to-boost-performance/',
      title: 'Sakana AI’s Darwin-Gödel Machine evolves by rewriting its own code',
      publishedAt: '2025',
      whyRelevant: '科技媒体对 DGM 的独立报道，佐证主题的行业关注度。',
      confidence: 0.8,
      status: 'source_pack_review',
    },
    // implementation_signal
    {
      id: 'se_reflexion_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/noahshinn',
      url: 'https://github.com/noahshinn/reflexion',
      title: 'noahshinn/reflexion',
      publishedAt: null,
      whyRelevant: 'Reflexion 官方代码，自我反思 agent 的可运行实现。',
      confidence: 0.95,
    },
    {
      id: 'se_voyager_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/MineDojo',
      url: 'https://github.com/MineDojo/Voyager',
      title: 'MineDojo/Voyager',
      publishedAt: null,
      whyRelevant: 'Voyager 官方代码，含自动课程 + skill library 全链路实现。',
      confidence: 0.95,
    },
    {
      id: 'se_dgm_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/jennyzzt',
      url: 'https://github.com/jennyzzt/dgm',
      title: 'jennyzzt/dgm (Darwin Gödel Machine)',
      publishedAt: null,
      whyRelevant: 'DGM 官方开源，自改代码 agent 的种群进化实现。',
      confidence: 0.9,
    },
  ],
  edges: [
    {
      fromId: 'se_dgm_2025',
      toId: 'se_godel_machine_2003',
      relationType: 'inspired_by',
      confidence: 0.85,
      evidenceNote: 'DGM 以 Schmidhuber 的 Gödel Machine 为理论谱系与命名来源，改用经验验证替代形式化证明。',
    },
    {
      fromId: 'se_dgm_2025',
      toId: 'se_adas_2024',
      relationType: 'builds_on',
      confidence: 0.85,
      evidenceNote: '同作者线（Hu/Lu/Clune），DGM 把 ADAS 的"meta agent 编程出新 agent"推进到 agent 自改自身代码。',
    },
    {
      fromId: 'se_survey_comprehensive_2025',
      toId: 'se_reflexion_2023',
      relationType: 'cites_as_foundation',
      confidence: 0.8,
      evidenceNote: '综述把 Reflexion 列为自进化反馈闭环的奠基范式之一。',
    },
    {
      fromId: 'se_survey_comprehensive_2025',
      toId: 'se_voyager_2023',
      relationType: 'cites_as_foundation',
      confidence: 0.8,
      evidenceNote: '综述把 Voyager 的 skill library 作为"技能积累"维度的代表。',
    },
    {
      fromId: 'se_reflexion_2023',
      toId: 'se_star_2022',
      relationType: 'extends',
      confidence: 0.75,
      evidenceNote: 'Reflexion 把 STaR"从自身正确输出学习"从训练侧推广到推理时的语言反馈循环。',
    },
    {
      fromId: 'se_voyager_2023',
      toId: 'se_self_refine_2023',
      relationType: 'shares_mechanism',
      confidence: 0.7,
      evidenceNote: '两者都用"同一 LLM 自我验证/自我反馈再精炼"的无训练迭代机制。',
    },
    {
      fromId: 'se_mit_techreview_2025',
      toId: 'se_sakana_dgm_blog_2025',
      relationType: 'reports_on',
      confidence: 0.85,
      evidenceNote: '权威媒体报道直接以 DGM 为"AI 自我改进"的代表案例。',
    },
    {
      fromId: 'se_dgm_repo',
      toId: 'se_dgm_2025',
      relationType: 'open_implements',
      confidence: 0.9,
      evidenceNote: 'jennyzzt/dgm 是 DGM 论文的官方开源实现。',
    },
  ],
  reviewNotes:
    'Deep-core 2026-06-21: 17 sources / 8 edges, arXiv ids verified (2303.11366 Reflexion, 2305.16291 Voyager, 2203.14465 STaR, 2303.17651 Self-Refine, 2505.22954 DGM, 2408.08435 ADAS, 2508.07407 + 2507.21046 surveys). Schmidhuber Gödel Machine via IDSIA official page. Roles all >=2.',
};

const WORLD_MODELS: ThreadSpec = {
  slug: 'world-models',
  title: 'World Models (世界模型)',
  updatedAt: '2026-06-21',
  category: 'foundation_models',
  tags: ['world-models', 'jepa', 'genie', 'world-simulator', 'spatial-intelligence'],
  aliases: ['World Models', '世界模型', 'JEPA', 'world simulator', 'spatial intelligence'],
  definitionDraft:
    'A world model learns an internal, compressed, predictable and interactive representation of an environment, used to simulate and predict how the world changes in response to actions — not merely to continue text or reconstruct pixels.',
  whyNow:
    'In 2024–2026 world models became an industry mainline: one camp pushes video generation toward “world simulators” (Sora), another argues autoregressive LLMs lack physics/causality and needs JEPA (LeCun), and a third pursues spatial intelligence / 3D world generation (Fei-Fei Li’s World Labs).',
  useBoundary:
    'Focus on whether a model builds a predictable internal representation of the world (JEPA, Genie, video-as-world-simulator, 3D world generation). Exclude pure video-generation aesthetics/quality.',
  sources: [
    // paper_foundation
    {
      id: 'wm_ha_2018',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Ha & Schmidhuber)',
      url: 'https://arxiv.org/abs/1803.10122',
      title: 'World Models',
      publishedAt: '2018-03',
      whyRelevant: '奠基论文：VAE+RNN 学环境压缩时空表征，智能体在"梦"里训练再迁移。',
      confidence: 1.0,
    },
    {
      id: 'wm_genie_2024',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Bruce et al., Google DeepMind)',
      url: 'https://arxiv.org/abs/2402.15391',
      title: 'Genie: Generative Interactive Environments',
      publishedAt: '2024-02',
      whyRelevant: '11B 基础世界模型，从无标注网络视频学潜动作，逐帧可玩。',
      confidence: 1.0,
    },
    {
      id: 'wm_dreamerv3_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Hafner et al.)',
      url: 'https://arxiv.org/abs/2301.04104',
      title: 'Mastering Diverse Domains through World Models (DreamerV3)',
      publishedAt: '2023-01',
      whyRelevant: '通用世界模型 RL 算法，首个从零在 Minecraft 挖到钻石。',
      confidence: 1.0,
    },
    {
      id: 'wm_ijepa_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Assran et al., Meta)',
      url: 'https://arxiv.org/abs/2301.08243',
      title: 'I-JEPA: Self-Supervised Learning from Images with a Joint-Embedding Predictive Architecture',
      publishedAt: '2023-01',
      whyRelevant: 'JEPA 首个图像落地：在表征空间预测目标块，非生成式。',
      confidence: 1.0,
    },
    {
      id: 'wm_vjepa2_2025',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Meta AI)',
      url: 'https://arxiv.org/abs/2506.09985',
      title: 'V-JEPA 2: Self-Supervised Video Models Enable Understanding, Prediction and Planning',
      publishedAt: '2025-06',
      whyRelevant: '100 万小时视频预训练 + 机器人轨迹，做潜动作世界模型零样本机械臂规划。',
      confidence: 1.0,
    },
    // official_definition
    {
      id: 'wm_jepa_blog',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'ai.meta.com (Yann LeCun)',
      url: 'https://ai.meta.com/blog/yann-lecun-ai-model-i-jepa/',
      title: 'A Path Towards Autonomous Machine Intelligence (JEPA / I-JEPA)',
      publishedAt: '2023-06',
      whyRelevant: 'LeCun 蓝图：JEPA 作为"世界模型模块"，在抽象嵌入空间预测而非重建像素。',
      confidence: 0.9,
    },
    {
      id: 'wm_sora_simulator_2024',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'openai.com',
      url: 'https://openai.com/index/video-generation-models-as-world-simulators/',
      title: 'Video generation models as world simulators (Sora 技术报告)',
      publishedAt: '2024-02',
      whyRelevant: '官方主张视频生成 scaling 是通向通用物理世界模拟器的路径。',
      confidence: 0.9,
    },
    {
      id: 'wm_genie3_blog_2025',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'deepmind.google',
      url: 'https://deepmind.google/blog/genie-3-a-new-frontier-for-world-models/',
      title: 'Genie 3: A new frontier for world models',
      publishedAt: '2025-08',
      whyRelevant: '首个实时交互通用世界模型，720p/24fps、文本生成可导航 3D 世界。',
      confidence: 0.9,
    },
    {
      id: 'wm_worldlabs_about',
      role: 'official_definition',
      sourceKind: 'official_docs',
      sourceOwner: 'worldlabs.ai (Fei-Fei Li 等)',
      url: 'https://www.worldlabs.ai/about',
      title: 'World Labs — About / Spatial Intelligence',
      publishedAt: '2024',
      whyRelevant: '官方自述"空间智能公司"，构建感知/生成/推理/交互 3D 的大世界模型。',
      confidence: 0.9,
    },
    // transcript_context
    {
      id: 'wm_lecun_mit_2026',
      role: 'transcript_context',
      sourceKind: 'news',
      sourceOwner: 'technologyreview.com',
      url: 'https://www.technologyreview.com/2026/01/22/1131661/yann-lecuns-new-venture-ami-labs/',
      title: 'LeCun: $1B to Replace LLMs—Why He Thinks They’re a Dead End',
      publishedAt: '2026-01-22',
      whyRelevant: 'LeCun 离开 Meta 创办 AMI Labs，押注世界模型/JEPA 反对自回归 LLM。',
      confidence: 0.9,
    },
    {
      id: 'wm_hassabis_decoder',
      role: 'transcript_context',
      sourceKind: 'news',
      sourceOwner: 'the-decoder.com',
      url: 'https://the-decoder.com/google-deepmind-ceo-demis-hassabi-says-world-models-are-making-progress-toward-agi/',
      title: 'DeepMind CEO Hassabis: world models making progress toward AGI',
      publishedAt: '2025',
      whyRelevant: 'Hassabis：LLM 缺物理/因果，世界模型 + 自动化实验是 AGI 两大关键。',
      confidence: 0.85,
    },
    {
      id: 'wm_feifei_substack_2025',
      role: 'transcript_context',
      sourceKind: 'blog',
      sourceOwner: 'drfeifei.substack.com (Fei-Fei Li)',
      url: 'https://drfeifei.substack.com/p/from-words-to-worlds-spatial-intelligence',
      title: 'From Words to Worlds: Spatial Intelligence is AI’s Next Frontier',
      publishedAt: '2025-11',
      whyRelevant: '李飞飞亲笔：LLM"博学但无身"，世界模型须尊重几何物理、融合多模。',
      confidence: 0.9,
    },
    // implementation_signal
    {
      id: 'wm_marble_worldlabs_2025',
      role: 'implementation_signal',
      sourceKind: 'official_blog',
      sourceOwner: 'worldlabs.ai',
      url: 'https://www.worldlabs.ai/blog/marble-world-model',
      title: 'Marble: A Multimodal World Model',
      publishedAt: '2025-11',
      whyRelevant: '首个商用世界模型产品：文本/图/视频/全景生成持久可下载 3D 环境。',
      confidence: 0.9,
    },
    {
      id: 'wm_ijepa_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/facebookresearch',
      url: 'https://github.com/facebookresearch/ijepa',
      title: 'facebookresearch/ijepa',
      publishedAt: null,
      whyRelevant: 'I-JEPA 官方实现，32×A100 训 ViT-Huge。',
      confidence: 0.9,
    },
    {
      id: 'wm_hardmaru_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/hardmaru',
      url: 'https://github.com/hardmaru/WorldModelsExperiments',
      title: 'hardmaru/WorldModelsExperiments',
      publishedAt: null,
      whyRelevant: '2018 World Models 官方实验代码（CarRacing/ViZDoom dream training）。',
      confidence: 0.8,
      status: 'source_pack_review',
    },
    // signal
    {
      id: 'wm_sora_survey_2024',
      role: 'signal',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Zhu, Wang et al.)',
      url: 'https://arxiv.org/abs/2405.03520',
      title: 'Is Sora a World Simulator? A Comprehensive Survey on General World Models',
      publishedAt: '2024-05',
      whyRelevant: '综述：盘点视频/自动驾驶等通用世界模型全景，质询 Sora 是否真模拟物理。',
      confidence: 0.85,
    },
    {
      id: 'wm_genie3_techtalks_2025',
      role: 'signal',
      sourceKind: 'blog',
      sourceOwner: 'bdtechtalks.com (Ben Dickson)',
      url: 'https://bdtechtalks.com/2025/08/07/deepmind-genie-3/',
      title: 'Genie 3: A new frontier (TechTalks 评测)',
      publishedAt: '2025-08-07',
      whyRelevant: '第三方解读 Genie 3 的承诺与局限（自回归架构、记忆一致性挑战）。',
      confidence: 0.8,
    },
  ],
  edges: [
    {
      fromId: 'wm_ha_2018',
      toId: 'wm_genie_2024',
      relationType: 'foundation_extends',
      confidence: 0.85,
      evidenceNote: 'Genie 把 Ha 的"压缩时空表征+动态预测"从单一 RL 环境推广到 11B 基础世界模型。',
    },
    {
      fromId: 'wm_ha_2018',
      toId: 'wm_dreamerv3_2023',
      relationType: 'foundation_extends',
      confidence: 0.8,
      evidenceNote: 'Dreamer 系列继承"在想象/梦中训练策略"思想，做成通用 RL 算法。',
    },
    {
      fromId: 'wm_jepa_blog',
      toId: 'wm_ijepa_2023',
      relationType: 'proposes_implements',
      confidence: 0.85,
      evidenceNote: 'LeCun 的 JEPA 蓝图由 I-JEPA 首次在图像上工程落地。',
    },
    {
      fromId: 'wm_ijepa_2023',
      toId: 'wm_vjepa2_2025',
      relationType: 'extends_to_video',
      confidence: 0.85,
      evidenceNote: '从图像表征预测扩展到视频 + 机器人规划，成动作条件世界模型。',
    },
    {
      fromId: 'wm_sora_simulator_2024',
      toId: 'wm_sora_survey_2024',
      relationType: 'claim_critiques',
      confidence: 0.8,
      evidenceNote: '综述直接质询 Sora 技报的"世界模拟器"主张，评估其物理理解程度。',
    },
    {
      fromId: 'wm_sora_simulator_2024',
      toId: 'wm_lecun_mit_2026',
      relationType: 'paradigm_opposes',
      confidence: 0.75,
      evidenceNote: 'Sora 代表生成式像素路线，LeCun 主张非生成式 JEPA，构成路线之争。',
    },
    {
      fromId: 'wm_feifei_substack_2025',
      toId: 'wm_marble_worldlabs_2025',
      relationType: 'vision_realizes',
      confidence: 0.85,
      evidenceNote: '李飞飞的"空间智能"主张由 World Labs 的 Marble 产品落地为商用世界模型。',
    },
    {
      fromId: 'wm_hassabis_decoder',
      toId: 'wm_genie3_blog_2025',
      relationType: 'leader_endorses_product',
      confidence: 0.8,
      evidenceNote: 'Hassabis 把世界模型列为 AGI 关键，Genie 3 是 DeepMind 的旗舰实证。',
    },
  ],
  reviewNotes:
    'Deep-core 2026-06-21: 17 sources / 8 edges, arXiv ids verified (1803.10122 World Models, 2402.15391 Genie, 2301.04104 DreamerV3, 2301.08243 I-JEPA, 2506.09985 V-JEPA 2, 2405.03520 Sora survey). hardmaru repo at source_pack_review. Roles all >=2.',
};

const EMBODIED_AI: ThreadSpec = {
  slug: 'embodied-ai',
  title: 'Embodied AI / VLA (具身智能)',
  updatedAt: '2026-06-21',
  category: 'foundation_models',
  tags: ['embodied-ai', 'vla', 'robotics', 'robot-foundation-models', 'manipulation'],
  aliases: ['Embodied AI', '具身智能', 'VLA', 'Vision-Language-Action', '视觉-语言-动作', 'robot foundation models'],
  definitionDraft:
    'Embodied AI / VLA brings the LLM/foundation-model paradigm into physical-world robot control: a single network sees images, hears natural-language instructions, and directly outputs robot actions, end-to-end fusing perception, understanding and execution.',
  whyNow:
    'Just as LLMs became foundation models for language, a general robot policy is becoming the robot foundation model for physical intelligence — one policy controls many robots and specializes to new tasks with little data. Three drivers: large cross-embodiment robot data (Open X-Embodiment), pretrained VLMs transferring web knowledge (RT-2), and a maturing open-source stack (Octo, OpenVLA, LeRobot, openpi).',
  useBoundary:
    'Focus on VLA models and robot foundation models for general manipulation/control. Exclude the specific autonomous-driving domain (autonomous-driving thread) and pure simulation/game RL agents.',
  sources: [
    // paper_foundation
    {
      id: 'em_rt1_2022',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Brohan et al., Google Robotics)',
      url: 'https://arxiv.org/abs/2212.06817',
      title: 'RT-1: Robotics Transformer for Real-World Control at Scale',
      publishedAt: '2022-12',
      whyRelevant: 'VLA 路线奠基：35M Transformer，图+语言指令→离散化机械臂动作，3Hz 实时。',
      confidence: 1.0,
    },
    {
      id: 'em_rt2_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Google DeepMind)',
      url: 'https://arxiv.org/abs/2307.15818',
      title: 'RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control',
      publishedAt: '2023-07',
      whyRelevant: '"VLA"一词代表作，把动作当文本 token 生成，联合微调 VLM 得涌现泛化。',
      confidence: 1.0,
    },
    {
      id: 'em_openx_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (21 机构联合)',
      url: 'https://arxiv.org/abs/2310.08864',
      title: 'Open X-Embodiment: Robotic Learning Datasets and RT-X Models',
      publishedAt: '2023-10',
      whyRelevant: '跨本体大数据奠基：22 机器人/527 技能，RT-X 显示正向迁移（ICRA 2024）。',
      confidence: 1.0,
    },
    {
      id: 'em_octo_2024',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (UC Berkeley/Stanford/CMU/GDM)',
      url: 'https://arxiv.org/abs/2405.12213',
      title: 'Octo: An Open-Source Generalist Robot Policy',
      publishedAt: '2024-05',
      whyRelevant: '开源通用策略，Transformer+diffusion，800k OXE episodes 预训练。',
      confidence: 1.0,
    },
    {
      id: 'em_pi0_2024',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Physical Intelligence)',
      url: 'https://arxiv.org/abs/2410.24164',
      title: 'π0: A Vision-Language-Action Flow Model for General Robot Control',
      publishedAt: '2024-10',
      whyRelevant: 'flow matching 接 PaliGemma，10000 小时数据，叠衣服等长程灵巧任务。',
      confidence: 1.0,
    },
    {
      id: 'em_openvla_2024',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Stanford/GDM/MIT/PI/Berkeley)',
      url: 'https://arxiv.org/abs/2406.09246',
      title: 'OpenVLA: An Open-Source Vision-Language-Action Model',
      publishedAt: '2024-06',
      whyRelevant: '7B 开源 VLA，Llama2+DINOv2/SigLIP，970k 演示，超 RT-2-X 55B。',
      confidence: 1.0,
    },
    {
      id: 'em_pi05_2025',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Physical Intelligence)',
      url: 'https://arxiv.org/abs/2504.16054',
      title: 'π0.5: a VLA Model with Open-World Generalization',
      publishedAt: '2025-04',
      whyRelevant: '进阶到全新未见家庭环境清理厨房/卧室，环境多样性是关键。',
      confidence: 1.0,
    },
    // official_definition
    {
      id: 'em_rt2_blog_2023',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'deepmind.google',
      url: 'https://deepmind.google/blog/rt-2-new-model-translates-vision-and-language-into-action/',
      title: 'RT-2: New model translates vision and language into action',
      publishedAt: '2023-07',
      whyRelevant: '官方对 VLA 概念的权威表述与可视化解读。',
      confidence: 0.9,
    },
    {
      id: 'em_pi0_blog_2024',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'pi.website (Physical Intelligence)',
      url: 'https://www.pi.website/blog/pi0',
      title: 'π0: Our First Generalist Policy',
      publishedAt: '2024-10',
      whyRelevant: '官方提出"机器人基础模型"愿景，叠衣服/装纸箱 demo 一手定义。',
      confidence: 0.9,
    },
    {
      id: 'em_pi05_blog_2025',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'pi.website (Physical Intelligence)',
      url: 'https://www.pi.website/blog/pi05',
      title: 'A VLA with Open-World Generalization (π0.5)',
      publishedAt: '2025-04',
      whyRelevant: '官方阐释开放世界泛化目标与两阶段训练法。',
      confidence: 0.9,
    },
    {
      id: 'em_gemini_robotics_blog_2025',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'deepmind.google',
      url: 'https://deepmind.google/blog/gemini-robotics-brings-ai-into-the-physical-world/',
      title: 'Introducing Gemini Robotics and Gemini Robotics-ER',
      publishedAt: '2025-03',
      whyRelevant: '大厂入场信号+官方定义：基于 Gemini 2.0 的 VLA + 具身推理 ER。',
      confidence: 0.9,
    },
    // transcript_context
    {
      id: 'em_levine_twiml_2025',
      role: 'transcript_context',
      sourceKind: 'podcast',
      sourceOwner: 'TWIML AI Podcast',
      url: 'https://open.spotify.com/episode/6YgfanrTvBKpHVrAEueBnN',
      title: 'π0: A Foundation Model for Robotics with Sergey Levine — TWIML #719',
      publishedAt: '2025-02',
      whyRelevant: 'Levine 亲述 π0 架构（VLM+action expert）与预训练/后训练数据哲学。',
      confidence: 0.85,
    },
    {
      id: 'em_finn_iclr_2025',
      role: 'transcript_context',
      sourceKind: 'talk',
      sourceOwner: 'ICLR 2025 (Chelsea Finn)',
      url: 'https://iclr.cc/virtual/2025/10000222',
      title: 'ICLR 2025 Invited Talk: Data-Driven Pre/Post-Training for Robot Foundation Models',
      publishedAt: '2025-04',
      whyRelevant: 'Finn 受邀演讲，机器人基础模型的预训练 + 后训练配方。',
      confidence: 0.85,
    },
    // implementation_signal
    {
      id: 'em_lerobot_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/huggingface',
      url: 'https://github.com/huggingface/lerobot',
      title: 'huggingface/lerobot',
      publishedAt: null,
      whyRelevant: '"机器人界的 Transformers"，PyTorch 模型/数据集/真机工具链。',
      confidence: 0.95,
    },
    {
      id: 'em_openpi_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/Physical-Intelligence',
      url: 'https://github.com/Physical-Intelligence/openpi',
      title: 'Physical-Intelligence/openpi',
      publishedAt: '2025-02',
      whyRelevant: '官方开源 π0/π0.5 权重与微调代码，1-20 小时数据即可调到新任务。',
      confidence: 0.95,
    },
    // signal
    {
      id: 'em_robotreport_pi0_2025',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'therobotreport.com',
      url: 'https://www.therobotreport.com/physical-intelligence-open-sources-pi0-robotics-foundation-model/',
      title: 'Physical Intelligence open-sources Pi0 robotics foundation model',
      publishedAt: '2025-02-07',
      whyRelevant: '行业媒体报道开源事件，类比开源 LLM 加速作用。',
      confidence: 0.85,
    },
    {
      id: 'em_venturebeat_lerobot_2024',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'venturebeat.com',
      url: 'https://venturebeat.com/automation/hugging-face-launches-lerobot-open-source-robotics-code-library',
      title: 'Hugging Face launches LeRobot open source robotics code library',
      publishedAt: '2024-05',
      whyRelevant: '产业信号：HF 把"democratize 机器人 AI"作为战略叙事。',
      confidence: 0.8,
      status: 'source_pack_review',
    },
  ],
  edges: [
    {
      fromId: 'em_rt1_2022',
      toId: 'em_rt2_2023',
      relationType: 'extends',
      confidence: 0.9,
      evidenceNote: 'RT-2 在 RT-1 的离散动作 token 思路上，叠加预训练 VLM 的网络知识迁移。',
    },
    {
      fromId: 'em_openx_2023',
      toId: 'em_rt2_2023',
      relationType: 'provides_data_for',
      confidence: 0.85,
      evidenceNote: 'OXE 的跨本体大数据训出 RT-2-X，OpenVLA 论文以 RT-2-X 为对比基线。',
    },
    {
      fromId: 'em_openx_2023',
      toId: 'em_octo_2024',
      relationType: 'provides_data_for',
      confidence: 0.85,
      evidenceNote: 'Octo 在 OXE 的 80 万 episodes 上预训练，是其数据底座。',
    },
    {
      fromId: 'em_openvla_2024',
      toId: 'em_rt2_blog_2023',
      relationType: 'outperforms',
      confidence: 0.8,
      evidenceNote: 'OpenVLA 7B 用 7 倍更少参数，任务成功率绝对值超 RT-2-X 55B。',
    },
    {
      fromId: 'em_pi0_2024',
      toId: 'em_pi0_blog_2024',
      relationType: 'official_announcement_of',
      confidence: 0.9,
      evidenceNote: '官博是 π0 论文的一手发布与愿景陈述。',
    },
    {
      fromId: 'em_pi0_2024',
      toId: 'em_pi05_2025',
      relationType: 'extends',
      confidence: 0.85,
      evidenceNote: 'π0.5 在 π0 基础上换两阶段训练，目标从"会做任务"升级到"泛化到全新家庭"。',
    },
    {
      fromId: 'em_pi0_2024',
      toId: 'em_levine_twiml_2025',
      relationType: 'authored_explains',
      confidence: 0.8,
      evidenceNote: 'π0 论文一作 Levine 在播客口述同一模型的架构与训练哲学。',
    },
    {
      fromId: 'em_openpi_repo',
      toId: 'em_pi0_2024',
      relationType: 'open_implements',
      confidence: 0.9,
      evidenceNote: 'openpi 是 π0/π0.5 论文的官方开源权重与代码实现。',
    },
  ],
  reviewNotes:
    'Deep-core 2026-06-21: 17 sources / 8 edges, all arXiv ids verified (2212.06817 RT-1, 2307.15818 RT-2, 2310.08864 Open X-Embodiment, 2405.12213 Octo, 2410.24164 π0, 2406.09246 OpenVLA, 2504.16054 π0.5). Boundary held vs autonomous-driving. Roles all >=2.',
};

const HARNESS_ENGINEERING: ThreadSpec = {
  slug: 'harness-engineering',
  title: 'Harness Engineering (智能体脚手架)',
  updatedAt: '2026-06-21',
  category: 'agentic_infrastructure',
  tags: ['agent-harness', 'scaffolding', 'agent-loop', 'tool-design', 'agent-runtime'],
  aliases: ['Harness Engineering', '智能体脚手架', 'agent harness', 'agent scaffolding', 'the harness'],
  definitionDraft:
    'Harness Engineering is the practice of designing the runtime framework around an LLM — tool exposure and schemas, context plumbing, the agent main loop, permissions and sandboxing, sub-agent dispatch, error recovery and stopping conditions — i.e. how the model’s output actually touches the world.',
  whyNow:
    'Anthropic explicitly calls the Claude Agent SDK "a general-purpose agent harness" and argues that even a frontier model running across many context windows performs poorly without a well-designed harness; in 2026 "agent harness engineering" was named as its own discipline (O’Reilly Radar, awesome lists, vendor harness docs).',
  useBoundary:
    'Focus on the runtime framework/scaffolding layer around a model (loop, tools, context, guardrails, sub-agents). Distinct from loop-engineering (human-designed automation loops), context-engineering (what goes in the window), and agentic-coding (the coding capability itself).',
  sources: [
    // official_definition
    {
      id: 'ha_building_effective_agents',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'anthropic.com',
      url: 'https://www.anthropic.com/engineering/building-effective-agents',
      title: 'Building effective agents',
      publishedAt: '2024-12-19',
      whyRelevant: '提出 ACI（agent-computer interface）概念，主张投入做工具/动作空间设计如同做 HCI——harness 工具层奠基性论述。',
      confidence: 0.95,
    },
    {
      id: 'ha_harness_design',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'anthropic.com (Prithvi Rajasekaran)',
      url: 'https://www.anthropic.com/engineering/harness-design-long-running-apps',
      title: 'Harness design for long-running application development',
      publishedAt: '2026-03-24',
      whyRelevant: 'Anthropic 官方用 "the harness" 一词，讲 initializer agent / 上下文重置 / sprint contract。',
      confidence: 0.9,
    },
    {
      id: 'ha_seeing_like_agent',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'claude.com (Thariq Shihipar)',
      url: 'https://claude.com/blog/seeing-like-an-agent',
      title: 'Seeing like an agent: how we design tools in Claude Code',
      publishedAt: '2026-03',
      whyRelevant: 'Claude Code 团队讲如何设计 agent 动作空间：fewer tools beat more、渐进式披露。',
      confidence: 0.85,
      status: 'source_pack_review',
    },
    {
      id: 'ha_openai_agents_sdk',
      role: 'official_definition',
      sourceKind: 'official_docs',
      sourceOwner: 'openai.github.io',
      url: 'https://openai.github.io/openai-agents-python/agents/',
      title: 'OpenAI Agents SDK — Agents / Runner docs',
      publishedAt: '2025',
      whyRelevant: '四原语（Agents/Tools/Handoffs/Guardrails）+ Runner.run() 主循环，另一家对 harness 的官方框架化。',
      confidence: 0.9,
    },
    {
      id: 'ha_agent_sdk_overview',
      role: 'official_definition',
      sourceKind: 'official_docs',
      sourceOwner: 'platform.claude.com',
      url: 'https://platform.claude.com/docs/en/agent-sdk/overview',
      title: 'Claude Agent SDK overview',
      publishedAt: '2026',
      whyRelevant: '官方称 Claude Agent SDK 为 "general-purpose agent harness"，agent loop/tools/context 暴露为 SDK。',
      confidence: 0.9,
    },
    // paper_foundation（诚实：无 harness 同名奠基论文，用 ACI/ReAct 代替）
    {
      id: 'ha_swe_agent_aci_2024',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Yang, Jimenez, Press et al., Princeton, NeurIPS 2024)',
      url: 'https://arxiv.org/abs/2405.15793',
      title: 'SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering',
      publishedAt: '2024-05',
      whyRelevant: '把"interface 设计影响 agent 表现"做成实证，正式提出 ACI——harness 工具接口最接近真论文的奠基工作。',
      confidence: 1.0,
      reviewNotes: 'Harness Engineering 无同名奠基论文，用 SWE-agent ACI 作工具层奠基代替（已核 2405.15793）。',
    },
    {
      id: 'ha_react_2022',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Yao et al., Princeton/Google)',
      url: 'https://arxiv.org/abs/2210.03629',
      title: 'ReAct: Synergizing Reasoning and Acting in Language Models',
      publishedAt: '2022-10',
      whyRelevant: 'reasoning+acting 交错范式，是几乎所有 agent 主循环（think→act→observe）的理论原型。',
      confidence: 1.0,
      reviewNotes: '作 agent 主循环理论原型代替缺失的 harness 奠基论文。',
    },
    // implementation_signal
    {
      id: 'ha_claude_agent_sdk_repo',
      role: 'implementation_signal',
      sourceKind: 'official_docs',
      sourceOwner: 'code.claude.com',
      url: 'https://code.claude.com/docs/en/agent-sdk/overview',
      title: 'Claude Agent SDK (docs)',
      publishedAt: '2026',
      whyRelevant: '开源可嵌入的 harness 实现：agent loop + 内置工具 + compaction 上下文管理，Python/TS 两版。',
      confidence: 0.85,
    },
    {
      id: 'ha_openai_agents_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/openai',
      url: 'https://github.com/openai/openai-agents-python',
      title: 'openai/openai-agents-python',
      publishedAt: null,
      whyRelevant: '生产级开源 harness 实现，Pydantic 自动生成工具 schema、handoff 子代理派发。',
      confidence: 0.9,
    },
    {
      id: 'ha_smolagents_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/huggingface',
      url: 'https://github.com/huggingface/smolagents',
      title: 'huggingface/smolagents',
      publishedAt: null,
      whyRelevant: '极简 code-agent harness，CodeAgent 用代码块表达动作；少量代码即完整 harness。',
      confidence: 0.9,
    },
    {
      id: 'ha_swe_agent_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/SWE-agent',
      url: 'https://github.com/SWE-agent/SWE-agent',
      title: 'SWE-agent/SWE-agent',
      publishedAt: null,
      whyRelevant: 'ACI 论文参考实现，可配置 agent 的命令/文件编辑接口——harness 接口设计活样本。',
      confidence: 0.9,
    },
    // transcript_context
    {
      id: 'ha_boris_pragmatic_2026',
      role: 'transcript_context',
      sourceKind: 'newsletter',
      sourceOwner: 'The Pragmatic Engineer (Gergely Orosz × Boris Cherny)',
      url: 'https://newsletter.pragmaticengineer.com/p/building-claude-code-with-boris-cherny',
      title: 'Building Claude Code with Boris Cherny',
      publishedAt: '2026-03',
      whyRelevant: 'Claude Code 负责人谈 agent loop、并行 agent、确定性 review——harness 设计取舍一手访谈。',
      confidence: 0.8,
      status: 'source_pack_review',
    },
    {
      id: 'ha_every_claude_code_2026',
      role: 'transcript_context',
      sourceKind: 'podcast',
      sourceOwner: 'Every (Boris Cherny / Cat Wu)',
      url: 'https://every.to/podcast/how-to-use-claude-code-like-the-people-who-built-it',
      title: 'How to Use Claude Code Like the People Who Built It',
      publishedAt: '2026',
      whyRelevant: 'Claude Code 创建者讲 agent loop、保持 context 精简、真实验证——harness 实操语境。',
      confidence: 0.8,
      status: 'source_pack_review',
    },
    // signal
    {
      id: 'ha_oreilly_harness_2026',
      role: 'signal',
      sourceKind: 'blog',
      sourceOwner: "oreilly.com/radar",
      url: 'https://www.oreilly.com/radar/agent-harness-engineering/',
      title: 'Agent Harness Engineering',
      publishedAt: '2026',
      whyRelevant: '把 harness 与 scaffolding 严格区分并系统命名为一门工程学科的代表性信号。',
      confidence: 0.85,
    },
    {
      id: 'ha_awesome_harness_2026',
      role: 'signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/ai-boost',
      url: 'https://github.com/ai-boost/awesome-harness-engineering',
      title: 'awesome-harness-engineering',
      publishedAt: null,
      whyRelevant: '专门聚合 harness 工程的 tools/patterns/evals/memory/MCP/permissions，证明已成独立领域。',
      confidence: 0.85,
    },
    {
      id: 'ha_addy_osmani_2026',
      role: 'signal',
      sourceKind: 'blog',
      sourceOwner: 'addyosmani.com (Addy Osmani)',
      url: 'https://addyosmani.com/blog/agent-harness-engineering/',
      title: 'Agent Harness Engineering',
      publishedAt: '2026',
      whyRelevant: 'Google 工程师界定 harness=loop+tools+context+guardrails+tracing，传播度高的 signal。',
      confidence: 0.8,
      status: 'source_pack_review',
    },
  ],
  edges: [
    {
      fromId: 'ha_building_effective_agents',
      toId: 'ha_swe_agent_aci_2024',
      relationType: 'concept_shared',
      confidence: 0.8,
      evidenceNote: 'Anthropic 的 ACI 一词与 SWE-agent 论文提出的 ACI 同名同源，工具接口设计是共同论点。',
    },
    {
      fromId: 'ha_building_effective_agents',
      toId: 'ha_seeing_like_agent',
      relationType: 'elaborates',
      confidence: 0.8,
      evidenceNote: '前者提出"像做 HCI 一样做 ACI"，后者落到"动作空间设计/fewer tools"具体实践。',
    },
    {
      fromId: 'ha_harness_design',
      toId: 'ha_agent_sdk_overview',
      relationType: 'same_owner_consistent',
      confidence: 0.85,
      evidenceNote: '同为 Anthropic，前者讲 harness 设计哲学，后者把同一套 harness 产品化为 SDK。',
    },
    {
      fromId: 'ha_agent_sdk_overview',
      toId: 'ha_openai_agents_sdk',
      relationType: 'parallel_implementation',
      confidence: 0.8,
      evidenceNote: '两家用不同原语（compaction vs guardrails/handoffs）解同一问题：把模型包成可运行 agent 的 harness。',
    },
    {
      fromId: 'ha_react_2022',
      toId: 'ha_swe_agent_aci_2024',
      relationType: 'foundation_of',
      confidence: 0.8,
      evidenceNote: 'ReAct 奠定 think-act-observe 主循环，SWE-agent 在此循环上加专用 ACI 工具接口。',
    },
    {
      fromId: 'ha_oreilly_harness_2026',
      toId: 'ha_harness_design',
      relationType: 'industrializes',
      confidence: 0.75,
      evidenceNote: '行业把 Anthropic 的一手实践抽象命名为 "harness engineering" 学科。',
    },
    {
      fromId: 'ha_awesome_harness_2026',
      toId: 'ha_openai_agents_repo',
      relationType: 'aggregates',
      confidence: 0.75,
      evidenceNote: '社区列表把这些实现源聚合为同一领域的工具谱系，反向证明 harness 已成独立工程对象。',
    },
    {
      fromId: 'ha_smolagents_repo',
      toId: 'ha_building_effective_agents',
      relationType: 'implements_pattern',
      confidence: 0.7,
      evidenceNote: 'smolagents 的极简 code-agent harness 正是"少而精工具+清晰动作空间"主张的落地。',
    },
  ],
  reviewNotes:
    'Deep-core 2026-06-21: 16 sources / 8 edges. NO arXiv paper named "harness" exists — paper_foundation honestly substituted with SWE-agent ACI (2405.15793, verified) + ReAct (2210.03629, verified). 4 sources at source_pack_review (seeing-like-agent, 2 Boris transcripts, Addy Osmani blog) pending fulltext capture. Roles all >=2.',
};

const AUTONOMOUS_DRIVING: ThreadSpec = {
  slug: 'autonomous-driving',
  title: 'Autonomous Driving (智能驾驶)',
  updatedAt: '2026-06-21',
  category: 'foundation_models',
  tags: ['autonomous-driving', 'end-to-end', 'driving-world-model', 'vla-driving', 'self-driving'],
  aliases: ['Autonomous Driving', '智能驾驶', '自动驾驶', 'end-to-end driving', 'self-driving'],
  definitionDraft:
    'Autonomous driving (AI view) uses a single/unified deep model to map raw sensor inputs end-to-end to vehicle planning and control, replacing the hand-written perception→prediction→planning→control pipeline. Three frontiers: end-to-end learning, generative driving world models, and VLA/large-model-driven driving.',
  whyNow:
    'Tesla FSD v12 replaced ~300k lines of C++ control code with neural networks ("photons in, controls out"); Wayve’s GAIA world models and Waymo’s EMMA push generative/VLM-driven driving. The end-to-end paradigm is Karpathy’s "Software 2.0" at its most thorough in driving.',
  useBoundary:
    'Focus on AI methodology frontiers in autonomous driving (end-to-end, driving world models, VLA-for-driving). Exclude general-purpose robotics/VLA (embodied-ai), whole-vehicle reviews and policy/regulation.',
  sources: [
    // signal
    {
      id: 'ad_tesla_fsdv12_2024',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'electrek.co',
      url: 'https://electrek.co/2024/03/12/tesla-pushes-new-fsd-beta-v12-update-no-new-note-but-musk-big-release/',
      title: 'Tesla pushes FSD Beta v12, Musk "big release"',
      publishedAt: '2024-03-12',
      whyRelevant: 'FSD v12 端到端转向的行业信号（30 万行 C++ → 神经网络）。',
      confidence: 0.85,
    },
    {
      id: 'ad_waymo_emma_blog_2024',
      role: 'signal',
      sourceKind: 'official_blog',
      sourceOwner: 'waymo.com',
      url: 'https://waymo.com/blog/2024/10/introducing-emma/',
      title: "Introducing Waymo's EMMA",
      publishedAt: '2024-10',
      whyRelevant: 'Waymo 用 Gemini 驱动端到端多模态驾驶模型的官方发布信号。',
      confidence: 0.85,
    },
    {
      id: 'ad_karpathy_warns_2025',
      role: 'signal',
      sourceKind: 'news',
      sourceOwner: 'electrek.co',
      url: 'https://electrek.co/2025/06/21/tesla-former-head-ai-warns-against-believing-self-driving-solved/',
      title: "Tesla's Former Head of AI warns self-driving not solved",
      publishedAt: '2025-06-21',
      whyRelevant: 'Karpathy 对端到端自动驾驶"已解决"论的怀疑式信号。',
      confidence: 0.85,
    },
    // official_definition
    {
      id: 'ad_wayve_av20',
      role: 'official_definition',
      sourceKind: 'official_docs',
      sourceOwner: 'wayve.ai',
      url: 'https://wayve.ai/technology/av2-0/',
      title: 'Wayve AV2.0 — Autonomy 2.0 data-driven approach',
      publishedAt: null,
      whyRelevant: 'Wayve 官方对"用单一端到端神经网络替代手写 AV 栈"的定义页。',
      confidence: 0.9,
    },
    {
      id: 'ad_waymo_aiml_blog_2024',
      role: 'official_definition',
      sourceKind: 'official_blog',
      sourceOwner: 'waymo.com',
      url: 'https://waymo.com/blog/2024/10/ai-and-ml-at-waymo/',
      title: 'Behind the Innovation: AI & ML at Waymo',
      publishedAt: '2024-10',
      whyRelevant: 'Waymo 官方阐述其大规模 ML/VLM/生成式方法的技术博客。',
      confidence: 0.9,
    },
    {
      id: 'ad_openpilot_repo',
      role: 'official_definition',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/commaai',
      url: 'https://github.com/commaai/openpilot',
      title: 'commaai/openpilot',
      publishedAt: null,
      whyRelevant: 'comma.ai 官方开源驾驶辅助系统，摄像头 AI 控转向/油门/刹车。',
      confidence: 0.9,
    },
    // transcript_context
    {
      id: 'ad_kendall_sequoia',
      role: 'transcript_context',
      sourceKind: 'podcast',
      sourceOwner: 'Sequoia Capital',
      url: 'https://www.sequoiacap.com/podcast/how-end-to-end-learning-created-autonomous-driving-2-0-wayve-ceo-alex-kendall/',
      title: 'How End-to-End Learning Created AD 2.0: Alex Kendall (Wayve)',
      publishedAt: null,
      whyRelevant: 'Wayve CEO Alex Kendall 谈端到端学习如何催生 AD 2.0。',
      confidence: 0.85,
    },
    {
      id: 'ad_ashok_cvpr_2023',
      role: 'transcript_context',
      sourceKind: 'video',
      sourceOwner: 'YouTube (Tesla / CVPR WAD)',
      url: 'https://www.youtube.com/watch?v=6x-Xb_uT7ts',
      title: '[CVPR’23 WAD] Keynote — Ashok Elluswamy, Tesla',
      publishedAt: '2023',
      whyRelevant: 'Tesla Autopilot 负责人讲 Occupancy Networks 与生成式模型。',
      confidence: 0.85,
    },
    {
      id: 'ad_karpathy_software2_2017',
      role: 'transcript_context',
      sourceKind: 'blog',
      sourceOwner: 'karpathy.medium.com (Andrej Karpathy)',
      url: 'https://karpathy.medium.com/software-2-0-a64152b37c35',
      title: 'Software 2.0',
      publishedAt: '2017-11',
      whyRelevant: '端到端范式思想源头：程序由数据编译而非手写。',
      confidence: 0.9,
    },
    // paper_foundation
    {
      id: 'ad_uniad_2022',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (OpenDriveLab/SenseTime)',
      url: 'https://arxiv.org/abs/2212.10156',
      title: 'Planning-oriented Autonomous Driving (UniAD)',
      publishedAt: '2022-12',
      whyRelevant: 'CVPR 2023 best paper，规划导向的统一端到端框架。',
      confidence: 1.0,
    },
    {
      id: 'ad_gaia1_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Wayve)',
      url: 'https://arxiv.org/abs/2309.17080',
      title: 'GAIA-1: A Generative World Model for Autonomous Driving',
      publishedAt: '2023-09',
      whyRelevant: '驾驶生成式世界模型奠基作，video+text+action→真实驾驶场景。',
      confidence: 1.0,
    },
    {
      id: 'ad_gaia2_2025',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Wayve)',
      url: 'https://arxiv.org/abs/2503.20523',
      title: 'GAIA-2: Controllable Multi-View Generative World Model',
      publishedAt: '2025-03',
      whyRelevant: '可控多视角驾驶世界模型，潜空间扩散 + 结构化条件。',
      confidence: 1.0,
    },
    {
      id: 'ad_e2e_survey_2023',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (OpenDriveLab, Li Chen et al., T-PAMI 2024)',
      url: 'https://arxiv.org/abs/2306.16927',
      title: 'End-to-end Autonomous Driving: Challenges and Frontiers',
      publishedAt: '2023-06',
      whyRelevant: '端到端 AD 权威综述，270+ 论文，论证端到端相对模块化的可扩展性优势。',
      confidence: 1.0,
    },
    {
      id: 'ad_drivevlm_2024',
      role: 'paper_foundation',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (清华 MARS Lab / 理想)',
      url: 'https://arxiv.org/abs/2402.12289',
      title: 'DriveVLM: The Convergence of Autonomous Driving and Large VLMs',
      publishedAt: '2024-02',
      whyRelevant: 'VLA 驾驶代表作，慢思考 VLM + 快系统双栈，已上量产车。',
      confidence: 1.0,
    },
    // implementation_signal
    {
      id: 'ad_carla_2017',
      role: 'implementation_signal',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (Dosovitskiy et al., Intel)',
      url: 'https://arxiv.org/abs/1711.03938',
      title: 'CARLA: An Open Urban Driving Simulator',
      publishedAt: '2017-11',
      whyRelevant: '开源城市驾驶仿真器，端到端模仿/强化学习训练基础设施。',
      confidence: 1.0,
    },
    {
      id: 'ad_nuscenes_2019',
      role: 'implementation_signal',
      sourceKind: 'paper',
      sourceOwner: 'arxiv.org (nuTonomy/Motional)',
      url: 'https://arxiv.org/abs/1903.11027',
      title: 'nuScenes: A multimodal dataset for autonomous driving',
      publishedAt: '2019-03',
      whyRelevant: '全传感器套件多模态数据集，端到端规划标准 benchmark。',
      confidence: 1.0,
    },
    {
      id: 'ad_uniad_repo',
      role: 'implementation_signal',
      sourceKind: 'github_repo',
      sourceOwner: 'github.com/OpenDriveLab',
      url: 'https://github.com/OpenDriveLab/UniAD',
      title: 'OpenDriveLab/UniAD',
      publishedAt: null,
      whyRelevant: 'UniAD 官方开源代码，端到端规划导向框架可复现实现。',
      confidence: 0.9,
    },
  ],
  edges: [
    {
      fromId: 'ad_e2e_survey_2023',
      toId: 'ad_uniad_2022',
      relationType: 'cites_as_milestone',
      confidence: 0.85,
      evidenceNote: '综述把 UniAD 列为规划导向端到端范式的代表性里程碑。',
    },
    {
      fromId: 'ad_uniad_2022',
      toId: 'ad_nuscenes_2019',
      relationType: 'evaluated_on',
      confidence: 0.85,
      evidenceNote: 'UniAD 在 nuScenes benchmark 上实例化并验证全栈任务。',
    },
    {
      fromId: 'ad_gaia2_2025',
      toId: 'ad_gaia1_2023',
      relationType: 'extends',
      confidence: 0.9,
      evidenceNote: 'GAIA-2 在 GAIA-1 基础上加多视角一致性与结构化可控条件。',
    },
    {
      fromId: 'ad_waymo_emma_blog_2024',
      toId: 'ad_drivevlm_2024',
      relationType: 'same_paradigm',
      confidence: 0.75,
      evidenceNote: '二者同属"大模型驱动驾驶"路线，用语言空间统一驾驶任务。',
    },
    {
      fromId: 'ad_tesla_fsdv12_2024',
      toId: 'ad_karpathy_software2_2017',
      relationType: 'embodies',
      confidence: 0.8,
      evidenceNote: 'FSD v12 把控制代码换成神经网络，是 Software 2.0 在驾驶的极致落地。',
    },
    {
      fromId: 'ad_wayve_av20',
      toId: 'ad_kendall_sequoia',
      relationType: 'explains',
      confidence: 0.8,
      evidenceNote: '播客访谈展开解释 AV2.0 官方页背后的端到端学习方法论。',
    },
    {
      fromId: 'ad_openpilot_repo',
      toId: 'ad_carla_2017',
      relationType: 'shares_domain',
      confidence: 0.7,
      evidenceNote: '二者同为端到端驾驶的开源/仿真基础设施（落地 vs 训练验证）。',
    },
  ],
  reviewNotes:
    'Deep-core 2026-06-21: 17 sources / 7 edges, all arXiv ids verified (2212.10156 UniAD, 2309.17080 GAIA-1, 2503.20523 GAIA-2, 2306.16927 e2e survey, 2402.12289 DriveVLM, 1711.03938 CARLA, 1903.11027 nuScenes). Boundary held vs embodied-ai. Roles all >=2.',
};

export const THREAD_SPECS: ThreadSpec[] = [
  RAG,
  DEEP_RESEARCH,
  MODEL_TRAINING,
  SELF_EVOLVING,
  WORLD_MODELS,
  EMBODIED_AI,
  HARNESS_ENGINEERING,
  AUTONOMOUS_DRIVING,
];
